### ISSUE TITLE
[META] YRT support

### ISSUE THREAD

**Issue by thomassth** [thomassth/ttc-bus-eta#99]
- [ ] Clean up data source
- [ ] Unify stops with TTC if applicable
- [ ] Bookmark to homepage
- [ ] BUG: navigate to line / stop page directly, without going through lines page will error out
